### PR TITLE
working directory that builds a release

### PR DESCRIPTION
**Pull request by andysheen**

### CODE REVIEW

**Comment by andysheen** [comment]
there's an issue with making a release when you already have one. Something to do with how it creates the tag. Other than that it's a good start.

**Comment by andysheen** [comment]
also, tested with a PiZ W!

**Comment by mikevanis** [comment]
Nice one!

**Comment by mikevanis** [comment]
With regards to the release, we should be able to copy the one over from YoYo, which just creates a draft release on a tag push. I'm thinking in the end, when we create a new tag on NaturewatchCameraServer, it triggers this to build and pull that tag (instead of master). I can help out with this next week, this is how we can link the two repos: https://github.community/t/triggering-by-other-repository/16163

**Pull request merged**
